[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NODE_HTTP = "true"
  NODE_VERSION = "18.19.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@genkit-ai/googleai"]
